In [81]:
%load_ext autoreload
%autoreload 2

import torch
import pickle
import os
import sys
sys.path.append('..')
import mdsim.models.pme_utils.layers as pme_layers

data = pickle.load(open('batch_data_example.pkl', 'rb'))
print(data)
print(data.cell.device)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
DataBatch(pos=[2100, 3], cell=[100, 3, 3], atomic_numbers=[2100], natoms=[100], y=[100], force=[2100, 3], fixed=[2100], sid=[100], fid=[100], id=[100], batch=[2100], ptr=[101])
cuda:0


In [99]:
pip install mendeleev

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 353.1/353.1 kB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 865.8/865.8 kB 33.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 29.9 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 614.3/614.3 kB 27.6 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.


In [102]:
import mendeleev

In [108]:
from rdkit import Chem
# https://www.rdkit.org/docs/source/rdkit.Chem.html

In [109]:
pt = Chem.GetPeriodicTable()

In [125]:
torch.sum(torch.randn(10,10),dim=[-1])

tensor([-1.7837,  3.7229, -2.4359, -4.5491,  0.8923, -0.2865,  0.8207, -4.1874,
        -0.6650, -3.0694])

In [121]:
ls = [0]
for i in range(118):
    ls.append(round(pt.GetRcovalent(i+1) / 0.529177 , 5))

In [162]:
meshgrid = pme_layers.init_particle_mesh(data.cell,3,pbc=True)
meshgrid.keys()

dict_keys(['cell', 'n_partition', 'meshgrid', 'meshgrid_flat', 'meshgrid_batch', 'pbc', 'super_n_partition', 'super_meshgrid', 'super_meshgrid_flat', 'super_meshgrid_batch', 'super_meshgrid_flat_to_normal_idx', 'super_meshgrid_flat_idx_to_batch'])

In [163]:
init_potential = pme_layers.initialize_potential(data.pos, data.atomic_numbers, data.batch, meshgrid)

In [165]:
init_potential.shape

torch.Size([100, 3, 3, 3, 16])

In [157]:
meshgrid["meshgrid"].shape

torch.Size([100, 3, 3, 3, 3])

In [117]:
round(pt.GetRcovalent(a) / 0.529177, 5)

0.28

In [103]:
from mendeleev.fetch import fetch_table

In [105]:
fetch_table('elements').keys()

Index(['annotation', 'atomic_number', 'atomic_radius', 'atomic_volume',
       'block', 'density', 'description', 'dipole_polarizability',
       'electron_affinity', 'electronic_configuration', 'evaporation_heat',
       'fusion_heat', 'group_id', 'lattice_constant', 'lattice_structure',
       'name', 'period', 'series_id', 'specific_heat_capacity', 'symbol',
       'thermal_conductivity', 'vdw_radius', 'covalent_radius_cordero',
       'covalent_radius_pyykko', 'en_pauling', 'en_allen', 'jmol_color',
       'cpk_color', 'proton_affinity', 'gas_basicity', 'heat_of_formation',
       'c6', 'covalent_radius_bragg', 'vdw_radius_bondi', 'vdw_radius_truhlar',
       'vdw_radius_rt', 'vdw_radius_batsanov', 'vdw_radius_dreiding',
       'vdw_radius_uff', 'vdw_radius_mm3', 'abundance_crust', 'abundance_sea',
       'molcas_gv_color', 'en_ghosh', 'vdw_radius_alvarez', 'c6_gb',
       'atomic_weight', 'atomic_weight_uncertainty', 'is_monoisotopic',
       'is_radioactive', 'cas', 'atomic_radiu

In [83]:
meshgrid = pme_layers.init_particle_mesh(data.cell,3,pbc=True)
meshgrid.keys()

dict_keys(['cell', 'n_partition', 'meshgrid', 'meshgrid_flat', 'meshgrid_batch', 'pbc', 'super_n_partition', 'super_meshgrid', 'super_meshgrid_flat', 'super_meshgrid_batch', 'super_meshgrid_flat_to_normal_idx', 'super_meshgrid_flat_idx_to_batch'])

In [84]:
mesh = meshgrid["meshgrid"]

In [90]:
batch_num = 1
mm = mesh[batch_num]

In [93]:
pos_batch = data.pos[data.batch==batch_num]
pos_batch.shape

torch.Size([21, 3])

In [97]:
atomic_numbers = data.atomic_numbers[data.batch==batch_num]
atomic_numbers.shape

torch.Size([21])

In [98]:
torch.linspace(0.5,5.0,16)

tensor([0.5000, 0.8000, 1.1000, 1.4000, 1.7000, 2.0000, 2.3000, 2.6000, 2.9000,
        3.2000, 3.5000, 3.8000, 4.1000, 4.4000, 4.7000, 5.0000])

In [24]:
mesh_grid['super_meshgrid'].shape

torch.Size([100, 18, 18, 18, 3])

In [29]:
mesh_grid['super_meshgrid_flat']

tensor([[-28.3333, -28.3333, -28.3333],
        [-28.3333, -28.3333, -25.0000],
        [-28.3333, -28.3333, -21.6667],
        ...,
        [ 28.3333,  28.3333,  21.6667],
        [ 28.3333,  28.3333,  25.0000],
        [ 28.3333,  28.3333,  28.3333]], device='cuda:0')

In [38]:
mesh_grid['meshgrid']

tensor([[[[[-15.0000, -15.0000, -15.0000],
           [-15.0000, -15.0000, -11.6667],
           [-15.0000, -15.0000,  -8.3333],
           ...,
           [-15.0000, -15.0000,   8.3333],
           [-15.0000, -15.0000,  11.6667],
           [-15.0000, -15.0000,  15.0000]],

          [[-15.0000, -11.6667, -15.0000],
           [-15.0000, -11.6667, -11.6667],
           [-15.0000, -11.6667,  -8.3333],
           ...,
           [-15.0000, -11.6667,   8.3333],
           [-15.0000, -11.6667,  11.6667],
           [-15.0000, -11.6667,  15.0000]],

          [[-15.0000,  -8.3333, -15.0000],
           [-15.0000,  -8.3333, -11.6667],
           [-15.0000,  -8.3333,  -8.3333],
           ...,
           [-15.0000,  -8.3333,   8.3333],
           [-15.0000,  -8.3333,  11.6667],
           [-15.0000,  -8.3333,  15.0000]],

          ...,

          [[-15.0000,   8.3333, -15.0000],
           [-15.0000,   8.3333, -11.6667],
           [-15.0000,   8.3333,  -8.3333],
           ...,
           

In [41]:
mesh_grid['super_meshgrid_idx'].unique()

tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
        112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
        140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153,
        154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167,
        168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 1

In [13]:
mesh_grid["meshgrid_flat"].shape

torch.Size([100, 1000, 3])

In [15]:
mesh_grid["meshgrid_batch"].shape

torch.Size([100000])

In [25]:
cell = torch.eye(3,3).unsqueeze(0)

In [27]:
cell[0,1]

tensor([0., 1., 0.])

In [4]:
grid_frac_axis = torch.linspace(0,1,10)

In [36]:
grid_frac = torch.meshgrid(grid_frac_axis, grid_frac_axis,grid_frac_axis)
grid_frac = torch.stack(grid_frac, dim=-1)

In [37]:
grid_frac.shape

torch.Size([10, 10, 10, 3])

In [39]:
grid_frac[0,0,0]

tensor([0., 0., 0.])

In [49]:
mesh_grid = torch.einsum("xyzl,blm->bxyzl", grid_frac, cell)

In [50]:
cell

tensor([[[1., 0., 0.],
         [0., 1., 0.],
         [0., 0., 1.]]])

In [51]:
mesh_grid.shape

torch.Size([1, 10, 10, 10, 3])

In [52]:
mesh_grid[0,1,1,0]

tensor([0.1111, 0.1111, 0.0000])